pipeline {
    agent { docker { image 'node:6.3' } }
    stages {
        stage('build') {
            steps {
                script {
                    echo 'project2 being run'
                }
            }
        }
    }
}
